#+TITLE: bootstrap-arch
#+LANGUAGE: en

This repository is a minimal version of my *ArchLinux* installer by just configuring
the encrypted partitions and configure *Arch* to boot those.

* Install

1. Build the installer with ~make~
2. Call the installer with no arguments or with the argument ~help~ to see the supported commands.
3. Generally you should do:
      1. Modify the provided configuration file
      2. > ~livedisk-init~ (optional)
      3. > ~disk-partition~
      4. > ~mount~
      5. > ~install~
      6. > ~chroot~ (optional: you can inspect the installed system)
      7. > ~umount~
      8. Reboot into the new system

* License
Copyright (C)  2017 nytthea

Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU General Public License, Version 3
or any later version published by the Free Software Foundation;
with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.

Code in this document is free software: you can redistribute it
and/or modify it under the terms of the GNU General Public
License as published by the Free Software Foundation, either
version 3 of the License, or (at your option) any later version.

This code is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
