#+TITLE: arch-installer
#+LANGUAGE: en

This repository is a minimal version of my *ArchLinux* installer by just configuring
the encrypted partitions and configure *Arch* to boot those.

* Preparations

1. Increase the cowspace size on the livedisk: ~mount -o size=1G,remount /run/archiso/cowspace~
2. Install required packages: ~pacman -Sy && pacman -S git make m4~
3. Pull the repository: ~git clone https://github.com/nytthea/arch-installer.git~
4. Run ~make~ inside the repository

* Install

1. Call the installer with no arguments or with the argument ~help~ to see the supported commands.
2. Generally you should do:
      1. Modify the provided configuration file
      2. > ~livedisk-init~ (optional)
      3. > ~disk-partition~
      4. > ~mount~
      5. > ~install~
      6. > ~chroot~ (optional: you can inspect the installed system)
      7. > ~umount~
      8. Reboot into the new system

* License
Copyright (C)  2017 nytthea

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
